<?php

$forgot_url	= $this->getUrl('*/*/forgotpassword', array('_secure'=>(!empty($_SERVER['HTTPS']) && $_SERVER['HTTPS']==='on')));
$http_mode	= (!empty($_SERVER['HTTPS']) && $_SERVER['HTTPS']==='on');

if ($http_mode) { 
    $forgot_url	= str_replace('http:', 'https:', $forgot_url);  
}

?>

<?php if ( ! Mage::getSingleton('customer/session')->isLoggedIn()): ?>

    <div id="easycheckoutbrasil_forgotbox" style="display: none;" class='op_login_area'>
        <div class='close_la' onclick='close_login();'></div>
        <h4 class="page-title">Esqueceu a senha?</h4>

        <form action="<?php echo $forgot_url ?>" method="post" id="forgot-password-form">

            <div class="boxcontent form_fields">

                <p>Informe o seu e-mail e você receberá uma nova senha.</p>

                <div class='full'>
                    <label><?php echo $this->__('Email') ?> </label><sup>*</sup>
                    <div class="data_area">
                        <input type="text" name="email" alt="email" id="email_address" class="input-text required-entry validate-email" value="<?php echo $this->htmlEscape($this->getEmailValue()) ?>" />
                    </div>
                </div>

            </div>

            <div class="buttons-set">

                <a href="javascript:void(0)" class="easycheckoutbrasil_loginlink f-left" onclick='open_login();'><small>&laquo; </small><?php echo $this->__('Back to Login') ?></a>
                <button type="submit" id="btn-forgot" class="button"><span>Enviar</span></button>
                <span class="please-wait" id="forgot-please-wait" style="display:none;">
                    <img src="<?php echo $this->getSkinUrl('images/opc-ajax-loader.gif') ?>" class="v-middle" alt=""/>
                </span>

            </div>

        </form>

        <script type="text/javascript">
        //<![CDATA[
            var forgotForm = new VarienForm('forgot-password-form', true);
        //]]>
        </script>
    </div>

<?php endif; ?>
