<div class="account-create">

    <div class="page-title"><h1>Cadastro</h1></div>

    <?php echo $this->getChildHtml('form_fields_before')?>
    <?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
    <?php echo $this->getChildHtml('customer.form.register.extra')?>

    <form action="<?php echo $this->getPostActionUrl() ?>" method="post" id="form-validate">

        <div class="fieldset">

            <input type="hidden" name="success_url" value="<?php echo $this->getSuccessUrl() ?>" />
            <input type="hidden" name="error_url" value="<?php echo $this->getErrorUrl() ?>" />

            <h2 class="legend">Dados Pessoais</h2>

            <ul class="form-list">

                <li class="fields">
                    <?php echo $this->getLayout()->createBlock('customer/widget_name')->setObject($this->getFormData())->setForceUseCustomerAttributes(true)->toHtml() ?>
                </li>

                <li class="fields boxpf">
                    <div class="customer-name">
                        <div class="field">
                            <label class="required"><em>*</em>Identidade</label>
                              <div class="input-box">
                                  <input type="text" name="rg" id="rg"  title="Identidade" class="input-text required-entry" />
                              </div>
                        </div>

                        <div class="field">
                            <label for="taxvat" class="required"><em>*</em>CPF</label>
                            <div class="input-box">
                                <input type="text" id="taxvat" name="taxvat" title="CPF" class="input-text required-entry cpf"  />
                            </div>
                        </div>
                    </div>
                </li>
                
                <li class="fields boxpf">
                    <div class="customer-name">
                        <div class="field">
                            <label for="telephone" class="required"><em>*</em>Telefone</label>
                            <div class="input-box">
                                <input type="text" name="telephone" id="telephone" value="<?php echo $this->escapeHtml($this->getFormData()->getTelephone()) ?>" title="Telefone" class="input-text <?php echo $this->helper('customer/address')->getAttributeValidationClass('telephone') ?>" />
                            </div>
                        </div>

                        <div class="field">
                            <label for="celular">Celular</label>
                            <div class="input-box">
                                <input type="text" name="celular" id="celular" value="<?php echo $this->escapeHtml($this->getFormData()->getCelular()) ?>" title="Celular" class="input-text" />
                            </div>
                        </div>
                    </div>
                </li>

            </ul>

        </div>

        <?php if($this->getShowAddressFields() ): ?>

            <div class="fieldset">

                <h2 class="legend">Endereço</h2>
                <input type="hidden" name="create_address" value="1" />

                <ul class="form-list">

                    <li class="wide">
                        <div class="field">
                            <label for="zip" class="required"><em>*</em>CEP</label>
                            <div class="input-box">
                                <input type="text" name="postcode" value="<?php echo $this->escapeHtml($this->getFormData()->getPostcode()) ?>" title="CEP" id="zip" class="input-text validate-zip-international <?php echo $this->helper('customer/address')->getAttributeValidationClass('postcode') ?>" onblur="buscarEndereco('<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_LINK, Mage::app()->getStore()->isCurrentlySecure()); ?>', $(this),$('street1'),$('street2'),$('street4'),$('city'),$('region_id'));" />
                            </div>
                        </div>
                    </li>

                    <li class="wide">
                        <div class="field">
                            <label for="street_1" class="required"><em>*</em>Endereço</label>
                            <div class="input-box">
                                <input type="text" name="street[]" value="<?php echo $this->escapeHtml($this->getFormData()->getStreet(1)) ?>" title="Endereço" id="street1" class="input-text required-entry" />
                            </div>
                        </div>
                    </li>

                    <li class="fields">
                        <div class="field">
                            <label for="street_2" class="required"><em>*</em>Número</label>
                            <div class="input-box">
                                <input type="text" name="street[]" value="<?php echo $this->escapeHtml($this->getFormData()->getStreet(2)) ?>" title="Número" id="street2" class="input-text required-entry" />
                            </div>
                        </div>
                        <div class="field">
                            <label for="street_3">Complemento</label>
                            <div class="input-box">
                                <input type="text" name="street[]" value="<?php echo $this->escapeHtml($this->getFormData()->getStreet(3)) ?>" title="Complemento" id="street3" class="input-text" />
                            </div>
                        </div>
                    </li>

                    <li class="fields">
                        <div class="field">
                            <label for="street_4" class="required"><em>*</em>Bairro</label>
                            <div class="input-box">
                                <input type="text" name="street[]" value="<?php echo $this->escapeHtml($this->getFormData()->getStreet(4)) ?>" title="Bairro" id="street4" class="input-text required-entry" />
                            </div>
                        </div>
                        <div class="field">
                            <label for="city" class="required"><em>*</em>Cidade</label>
                            <div class="input-box">
                                <input type="text" name="city" value="<?php echo $this->escapeHtml($this->getFormData()->getCity()) ?>" title="Cidade" class="input-text <?php echo $this->helper('customer/address')->getAttributeValidationClass('city') ?>" id="city" />
                            </div>
                        </div>
                    </li>

                    <li class="fields">
                        <div class="field">
                            <label for="region_id" class="required"><em>*</em>Estado</label>
                            <div class="input-box">
                                <select id="region_id" name="region_id" title="Estado" class="validate-select" style="display:none;">
                                    <option value="">Selecione</option>
                                </select>

                                <input type="text" id="region" name="region" value="<?php echo $this->escapeHtml($this->getRegion()) ?>" title="<?php echo $this->__('State/Province') ?>" class="input-text <?php echo $this->helper('customer/address')->getAttributeValidationClass('region') ?>" style="display:none;" />
                            </div>
                        </div>
                        <div class="field">
                                <label for="country" class="required"><em>*</em>País</label>
                            <div class="input-box">
                                <?php echo $this->getCountryHtmlSelect() ?>
                            </div>
                        </div>
                    </li>

                </ul>

                <input type="hidden" name="default_billing" value="1" />
                <input type="hidden" name="default_shipping" value="1" />

            </div>

        <?php endif; ?>

        <div class="fieldset">

            <h2 class="legend">Informações do Usuário</h2>

            <ul class="form-list">

                <li>
                    <label for="email_address" class="required"><em>*</em>E-mail</label>
                    <div class="input-box">
                        <input type="text" name="email" id="email_address" value="<?php echo $this->escapeHtml($this->getFormData()->getEmail()) ?>" title="E-mail" class="input-text validate-email required-entry" />
                    </div>
                </li>

                <?php if ($this->isNewsletterEnabled()): ?>
                    <li class="control">
                        <div class="input-box">
                            <input type="checkbox" name="is_subscribed" title="Receber ofertas e novidades" value="1" id="is_subscribed"<?php if($this->getFormData()->getIsSubscribed()): ?> checked="checked"<?php endif; ?> class="checkbox" />
                        </div>
                        <label for="is_subscribed">Receber ofertas e novidades</label>
                        <?php echo $this->getChildHtml('customer.form.register.newsletter')?>
                    </li>
                <?php endif ?>

                <li class="fields">
                    <div class="field">
                        <label for="password" class="required"><em>*</em>Senha</label>
                        <div class="input-box">
                            <input type="password" name="password" id="password" title="Senha" class="input-text required-entry validate-password" />
                        </div>
                    </div>

                    <div class="field">
                        <label for="confirmation" class="required"><em>*</em>Confirme a senha</label>
                        <div class="input-box">
                            <input type="password" name="confirmation" title="Confirme a senha" id="confirmation" class="input-text required-entry validate-cpassword" />
                        </div>
                    </div>
                </li>

                <?php echo $this->getChildHtml('form.additional.info'); ?>
            </ul>
        </div>

        <div class="buttons-set">
            <p class="required">* Preenchimento Obrigatório</p>
            <p class="back-link"><a href="<?php echo $this->escapeUrl($this->getBackUrl()) ?>" class="back-link"><small>&laquo; </small>Voltar</a></p>
            <button type="submit" title="Enviar" class="button"><span><span>Enviar</span></span></button>
        </div>
    </form>
</div>

<script type="text/javascript" src="<?php echo $this->getSkinUrl('js/jquery.js') ?>"></script>
<script type="text/javascript" src="<?php echo $this->getSkinUrl('js/maskedinput.min.js') ?>"></script>

<script type="text/javascript">

    var $j = jQuery.noConflict();

    $j(document).ready(function() {
        $j('input[name*="postcode"]').mask("99999-999");
        $j('input[name*="telephone"]').mask("(99) 9999999?99");
        $j('input[name*="celular"]').mask("(99) 9999999?99");
        $j('input[name*="taxvat"]').mask("999.999.999-99");
    });

</script>

<script type="text/javascript" src="<?php echo $this->getSkinUrl('js/funcoes.js') ?>"></script>

<script type="text/javascript">
//<![CDATA[
    var dataForm = new VarienForm('form-validate', true);
    <?php if($this->getShowAddressFields()): ?>
    $('country').setValue('<?php echo Mage::getStoreConfig('easycheckoutbrasil/general/country'); ?>');
    new RegionUpdater('country', 'region', 'region_id', <?php echo $this->helper('directory')->getRegionJson() ?>, undefined, 'zip');
    $j('label[for=region_id]').addClass('required').html("<em>*</em>Estado");
    <?php endif; ?>
//]]>
</script>
